// Command serve runs an HTTP API that embeds a user's query and returns the
// nearest chunks from Postgres+pgvector. It's a thin wrapper: all the real
// logic lives in internal/retrieve, internal/api, internal/embedding, and
// internal/store — this file just parses flags and wires them together.
//
// Requires the database schema to already exist — run `make migrate` (or
// `docker compose run --rm migrate`) first, same precondition cmd/ingest
// has.
package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"net/http"

	"github.com/MadonnaMat/go-rag-lab/internal/api"
	"github.com/MadonnaMat/go-rag-lab/internal/chat"
	"github.com/MadonnaMat/go-rag-lab/internal/chat/prompts"
	"github.com/MadonnaMat/go-rag-lab/internal/config"
	"github.com/MadonnaMat/go-rag-lab/internal/embedding"
	"github.com/MadonnaMat/go-rag-lab/internal/ingest"
	"github.com/MadonnaMat/go-rag-lab/internal/retrieve"
	"github.com/MadonnaMat/go-rag-lab/internal/store"

	_ "github.com/MadonnaMat/go-rag-lab/docs" // generated by `make swagger`; its init() registers the spec internal/api's /swagger/* route serves
)

// @title			go-rag-lab Query API
// @version		1.0
// @description	Embeds a query and returns the nearest chunks from Postgres+pgvector.
// @BasePath		/
func main() {
	addr := flag.String("addr", "", "address to listen on, e.g. :8080 (overrides SERVER_ADDR)")
	flag.Parse()

	if err := run(*addr); err != nil {
		log.Fatal(err)
	}
}

func run(addrFlag string) error {
	cfg, err := config.Load()
	if err != nil {
		return fmt.Errorf("load config: %w", err)
	}

	addr := cfg.ServerAddr
	if addrFlag != "" {
		addr = addrFlag
	}

	ctx := context.Background()

	provider, err := embedding.New(cfg.EmbeddingProvider, cfg.OllamaURL, cfg.OllamaEmbedModel)
	if err != nil {
		return fmt.Errorf("build embedding provider: %w", err)
	}

	s, err := store.Open(ctx, cfg.DatabaseURL)
	if err != nil {
		return fmt.Errorf("open store: %w", err)
	}
	defer s.Close()

	retriever := &retrieve.Retriever{Store: s, Provider: provider}

	chatClient := chat.NewOllamaChat(cfg.OllamaURL, cfg.OllamaChatModel)
	contextTokens, err := chatClient.ContextLength(ctx)
	if err != nil {
		log.Printf("warning: could not determine %s's context length, falling back to a default: %v", cfg.OllamaChatModel, err)
	}
	ingester := &ingest.Ingester{
		Store:        s,
		Provider:     provider,
		Summarizer:   chatClient,
		ChunkSize:    cfg.ChunkSize,
		ChunkOverlap: cfg.ChunkOverlap,
	}

	chatter := &chat.Chatter{
		Client:       chatClient,
		Retriever:    retriever,
		DefaultTopK:  cfg.TopK,
		SystemPrompt: prompts.System,
		// A lore_drop answer chains retrieve_documents -> lore_drop -> final
		// answer, a step past the bare retrieve-then-answer path — 5 leaves
		// headroom for a stray extra tool call without letting a weak model
		// loop indefinitely.
		MaxToolIterations: 5,
		ContextTokens:     contextTokens,
		Summaries:         s,
		Docs:              s,
		Loremaster:        ingester,
		LoreDir:           cfg.LoreDir,
	}

	handler := api.NewRouter(&api.Handler{Retriever: retriever, Chatter: chatter, DefaultTopK: cfg.TopK})

	log.Printf("listening on %s", addr)
	return http.ListenAndServe(addr, handler)
}
