package chat

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/MadonnaMat/go-rag-lab/internal/chat/tools"
	"github.com/MadonnaMat/go-rag-lab/internal/store"
)

// The capability interfaces the tools need are defined in internal/chat/tools;
// re-exported here so Chatter's fields and external callers keep one name.
type (
	// Retriever embeds a query and returns the nearest chunks.
	Retriever = tools.Retriever
	// DocLister lists every ingested document (list_resources).
	DocLister = tools.DocLister
	// Loremaster re-ingests one just-written document (lore_drop).
	Loremaster = tools.Loremaster
)

// SummaryStore is the subset of *store.Store chat needs to load the
// corpus-wide summary generated by cmd/ingest.
type SummaryStore interface {
	GetCorpusSummary(ctx context.Context) (string, error)
}

// Chatter orchestrates a tool-calling conversation with Ollama.
type Chatter struct {
	Client            *OllamaChat
	Retriever         Retriever
	DefaultTopK       int
	SystemPrompt      string
	MaxToolIterations int
	// ContextTokens is the model's real context window, from
	// OllamaChat.ContextLength — drives auto-compaction and the
	// context-usage events.
	ContextTokens int
	// Summaries, if set, is queried once per Run call for the current
	// corpus summary (generated by cmd/ingest), appended after
	// SystemPrompt — loaded fresh per request rather than cached at
	// startup, since ingestion can happen again while cmd/serve is
	// running. A lookup error or empty result is silently ignored: chat
	// still works without a summary.
	Summaries SummaryStore

	// Docs, Loremaster and LoreDir back the list_resources / get_resource /
	// lore_drop tools. Each is optional: a tool whose dependency is nil (or,
	// for the disk-backed tools, LoreDir == "") is omitted from
	// availableTools() and its dispatch case returns a structured error.
	Docs       DocLister
	Loremaster Loremaster
	// LoreDir is the directory get_resource reads .md files from and
	// lore_drop writes them to — the same directory cmd/ingest ingests.
	LoreDir string
}

// Message is one turn in a client-supplied conversation history.
type Message struct {
	Role    string
	Content string
}

type EventType int

const (
	EventToolCall EventType = iota
	EventToolResult
	EventThinking
	EventToken
	EventCompacting // the summarization call is running (no output yet)
	EventCompacted  // compaction finished; Summary holds the result
	EventVerifying
	EventRevised
	EventContextUsage
	EventSources // the documents the final answer drew on
	EventDone
	EventError
)

// SourceRef names one document the answer drew on, plus the indices of the
// retrieved chunks from it — enough for a client to fetch the doc and
// highlight the exact passages (see internal/api's /lore endpoint).
type SourceRef struct {
	File         string
	ChunkIndices []int
}

// Event is what Run emits as the conversation progresses.
type Event struct {
	Type       EventType
	ToolName   string
	ToolArgs   map[string]any
	ToolResult []toolResultChunk
	// ToolSummary is a human-readable one-liner describing a non-retrieval
	// tool's result (list_resources / get_resource / lore_drop) for the UI
	// status line — retrieval uses ToolResult instead.
	ToolSummary string
	// ToolPayload is the exact JSON a non-retrieval tool handed back to the
	// model, passed through to the SSE client so the UI can render it
	// (e.g. the document list from list_resources).
	ToolPayload   json.RawMessage
	Token         string
	Summary       string
	Revised       string
	UsedTokens    int
	ContextTokens int
	// Sources is set on EventSources: the documents the final answer drew on.
	Sources []SourceRef
	Err     error
}

const compactCommand = "/compact"

const defaultMaxToolIterations = 4

// Run drives the tool-call loop for one request's conversation, emitting
// Events via emit as it goes. Blocks until the conversation reaches a
// final answer, a /compact command completes, or an error/cap is hit.
func (c *Chatter) Run(ctx context.Context, history []Message, emit func(Event) error) error {
	if len(history) == 0 {
		return fmt.Errorf("history must not be empty")
	}

	messages := c.buildInitialMessages(ctx, history)

	if last := history[len(history)-1]; last.Role == "user" && strings.EqualFold(strings.TrimSpace(last.Content), compactCommand) {
		return c.runCompactCommand(ctx, messages[:len(messages)-1], emit)
	}

	return c.runLoop(ctx, messages, emit)
}

// buildInitialMessages prepends the system prompt (plus any stored corpus
// summary) to history, converted to wire-format messages.
func (c *Chatter) buildInitialMessages(ctx context.Context, history []Message) []chatMessage {
	systemPrompt := c.SystemPrompt
	if c.Summaries != nil {
		if summary, err := c.Summaries.GetCorpusSummary(ctx); err == nil && summary != "" {
			systemPrompt += "\n\n" + summary
		}
	}

	messages := make([]chatMessage, 0, len(history)+1)
	messages = append(messages, chatMessage{Role: "system", Content: systemPrompt})
	for _, m := range history {
		messages = append(messages, chatMessage{Role: m.Role, Content: m.Content})
	}
	return messages
}

// runCompactCommand handles a /compact message: it force-compacts
// messages regardless of the usual threshold and returns without calling
// the model at all.
func (c *Chatter) runCompactCommand(ctx context.Context, messages []chatMessage, emit func(Event) error) error {
	if err := emit(Event{Type: EventCompacting}); err != nil {
		return err
	}
	compacted, summary := c.compact(ctx, messages)
	if summary == "" {
		summary = "nothing to compact"
	}
	if err := emit(Event{Type: EventCompacted, Summary: summary}); err != nil {
		return err
	}
	if err := emit(Event{Type: EventContextUsage, UsedTokens: estimateTokens(compacted), ContextTokens: c.ContextTokens}); err != nil {
		return err
	}
	return emit(Event{Type: EventDone})
}

// runLoop is the main tool-call loop: compact if needed, stream one
// model turn, then either finalize (no tool call) or execute tool calls
// and loop again.
func (c *Chatter) runLoop(ctx context.Context, messages []chatMessage, emit func(Event) error) error {
	maxIterations := c.MaxToolIterations
	if maxIterations <= 0 {
		maxIterations = defaultMaxToolIterations
	}

	// Tracks once-per-turn tools (lore_drop) that have already run, across
	// every iteration of this one Run.
	succeeded := map[string]bool{}
	// Every chunk retrieved this turn, so finalize can name the sources the
	// answer drew on.
	var retrieved []store.SearchResult

	for iteration := 0; iteration < maxIterations; iteration++ {
		messages = c.maybeCompact(ctx, messages, emit)

		draft, sawToolCall, err := c.streamTurn(ctx, messages, emit)
		if err != nil {
			return c.emitFatal(emit, err)
		}

		if !sawToolCall {
			return c.finalize(ctx, messages, draft.Content, succeeded[tools.LoreDropName], retrieved, emit)
		}

		messages = append(messages, draft)
		toolMessages, err := c.executeToolCalls(ctx, draft.ToolCalls, succeeded, false, &retrieved, emit)
		if err != nil {
			return c.emitFatal(emit, err)
		}
		messages = append(messages, toolMessages...)
	}

	return c.emitFatal(emit, fmt.Errorf("tool-call loop exceeded max iterations (%d)", maxIterations))
}

// maybeCompact compacts messages if they've crossed compactThreshold of
// the model's context window. A compaction failure is non-fatal — the
// event still fires (with a fallback summary), but messages are only
// swapped in if compaction actually produced something.
func (c *Chatter) maybeCompact(ctx context.Context, messages []chatMessage, emit func(Event) error) []chatMessage {
	if c.ContextTokens <= 0 || estimateTokens(messages) <= int(compactThreshold*float64(c.ContextTokens)) {
		return messages
	}
	_ = emit(Event{Type: EventCompacting})
	compacted, summary := c.compact(ctx, messages)
	if summary == "" {
		return messages
	}
	_ = emit(Event{Type: EventCompacted, Summary: summary})
	return compacted
}

// streamTurn calls the model once, emitting EventThinking/EventToken for
// each streamed delta, and returns the accumulated assistant message plus
// whether it included tool calls.
func (c *Chatter) streamTurn(ctx context.Context, messages []chatMessage, emit func(Event) error) (chatMessage, bool, error) {
	var draft chatMessage
	var sawToolCall bool

	err := c.Client.Chat(ctx, messages, c.toolDefs(false), func(line chatStreamLine) error {
		if len(line.Message.ToolCalls) > 0 {
			sawToolCall = true
			draft.ToolCalls = append(draft.ToolCalls, line.Message.ToolCalls...)
		}
		if line.Message.Thinking != "" {
			draft.Thinking += line.Message.Thinking
			if err := emit(Event{Type: EventThinking, Token: line.Message.Thinking}); err != nil {
				return err
			}
		}
		if line.Message.Content != "" && !sawToolCall {
			draft.Content += line.Message.Content
			if err := emit(Event{Type: EventToken, Token: line.Message.Content}); err != nil {
				return err
			}
		}
		return nil
	})
	return draft, sawToolCall, err
}

// finalize runs the verification pass on a draft answer with no further
// tool calls, then emits the context-usage and done events. wroteToCorpus
// says whether a lore_drop succeeded this turn — if so, verify gets the
// read-only corpus tools to fact-check the write; otherwise it's a cheap
// single-shot check.
func (c *Chatter) finalize(ctx context.Context, messages []chatMessage, draftContent string, wroteToCorpus bool, retrieved []store.SearchResult, emit func(Event) error) error {
	finalContent, err := c.verify(ctx, messages, draftContent, wroteToCorpus, emit)
	if err != nil {
		return err
	}
	messages = append(messages, chatMessage{Role: "assistant", Content: finalContent})

	if sources := answerSources(finalContent, retrieved); len(sources) > 0 {
		if err := emit(Event{Type: EventSources, Sources: sources}); err != nil {
			return err
		}
	}

	if err := emit(Event{Type: EventContextUsage, UsedTokens: estimateTokens(messages), ContextTokens: c.ContextTokens}); err != nil {
		return err
	}
	return emit(Event{Type: EventDone})
}

// emitFatal emits EventError (best-effort) and returns err.
func (c *Chatter) emitFatal(emit func(Event) error, err error) error {
	_ = emit(Event{Type: EventError, Err: err})
	return err
}
